### PR TITLE
finished another LocalStorage task

### PR DESCRIPTION
**Pull request by Aamr-mohamed**
with a walkaround the useRef() returning object 
still remains the several users and the functionality of the two pages

### CODE REVIEW

**Review by se-omar — CHANGES_REQUESTED** [review]
```
    localStorage.setItem("emailCheck", svdEmail.current.value);
    localStorage.setItem("passwordCheck", svdPassword.current.value);
    const emailTemp = localStorage.getItem("emailCheck");
    const passwordTemp = localStorage.getItem("passwordCheck");
    if (emailTemp == email && passwordTemp == password) {
      navigate("/");
    } else {
      console.log("m4 4a8al");
    }
```
we have svdPassword.current.value and svdEmail.current.value, why are we saving them to localStorage, and then retrieving them from local storage, only to compare them to email and password.

just compare svdPassword.current.value to password, and svdEmail.current.value to email directly

**Comment by Aamr-mohamed** [comment]
const svdEmail = useRef();
svdEmail is an object u cant compare string to an object so that was the workaround

**Comment by se-omar** [comment]
can i do 
```
 if (svdEmail.current.value == email && svdPassword.current.value == password) {
      navigate("/");
    } else {
      console.log("m4 4a8al");
    }
```
?

**Comment by Aamr-mohamed** [comment]
I am disgraced for the rest of my life master

**Pull request merged**
